# Generated by Django 3.0.3 on 2020-03-14 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('send', '0003_screenrecords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScreenRecords',
            new_name='ScreenRecord',
        ),
    ]
