# Generated by Django 3.0.3 on 2020-03-17 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0005_historyfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historyfile',
            old_name='record',
            new_name='history',
        ),
    ]
