# Generated by Django 3.0.3 on 2020-04-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0007_blockedurl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlockedUrl',
        ),
    ]
