# Generated by Django 3.0.3 on 2020-04-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedurl',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
