# Generated by Django 3.0.3 on 2020-04-30 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_auto_20200429_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedurl',
            name='url',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
