# Generated by Django 3.0.3 on 2020-05-24 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('children', '0003_auto_20200430_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedurl',
            name='url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterUniqueTogether(
            name='blockedurl',
            unique_together={('url', 'user')},
        ),
    ]
