# Generated by Django 3.0.3 on 2020-05-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_auto_20200524_1737'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='blockedurl',
            unique_together=set(),
        ),
    ]
